version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      # Retrieve credentials and log in to ECR
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/groths89/cardgameengine # Replace with your ECR repo name
  build:
    commands:
      - echo Build started on `date`
      # Build the Docker image (using the modified Dockerfile)
      - docker build -t $REPOSITORY_URI:latest .
  post_build:
    commands:
      - echo Build completed on `date`
      # Tag the image
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION
      # Push the image to ECR
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION
      # Use SAM to deploy (CloudFormation takes the image from ECR)
      - sam deploy --template-file template.yaml --stack-name GameEngineStack --image-repositories ConnectHandlerUri=$REPOSITORY_URI --s3-bucket YourS3BucketName --capabilities CAPABILITY_IAM
artifacts:
  files:
    - template.yaml
